# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - bioc-release
sudo: true
cache: packages
bioc_required: true
bioc_use_devel: true
warnings_are_errors: false

r_check_args: '--ignore-vignettes --no-examples'

os:
  - linux
  - osx
osx_image: xcode9

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

r_binary_packages:
  - withr
  - knitr
  - crayon
  - roxygen2
  - testthat
  - rex
  - survminer
  - r6
  - whisker
  - jsonlite
  - httr
  - rcurl
  - bitops
  - dbi
  - rsqlite

bioc_packages:
  - BiocStyle
  - GenomicRanges
  - Biobase
  - affy
  - EDASeq
  - edgeR
  - biomaRt
  - IRanges
  - supraHex
  - S4Vectors
  - ComplexHeatmap
  - SummarizedExperiment
  - BiocGenerics
  - GenomicFeatures
  - TxDb.Hsapiens.UCSC.hg19.knownGene
  - limma
  - genefilter
  - ConsensusClusterPlus
  - pathview
  - clusterProfiler
  - BiocCheck
  - fgsea
  - GenomicInteractions
  - GO.db
  - DO.db
  - org.Hs.eg.db

r_github_packages:
  - tiagochst/ELMER.data
  - hfang-bristol/dnet
  - BioinformaticsFMRP/TCGAbiolinks

script: 
  - |
    travis_wait R CMD build .
    travis_wait 60 R CMD check ELMER*tar.gz

after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")

r_build_args:  --no-resave-data

notifications:
    slack: junkdnalab:KV8Dr7etoqqDQPsORdaZLOz2
    email: false
    on_success: never # default: change
    on_failure: always # default: always